import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "../components/Sidebar";
import Header from "../components/Header";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <SessionProvider>
          <div className="flex">
            <div className="bg-yellow-900 text-gray-200 max-w-[250px] h-screen overflow-y-auto md:min-w-[220px]">
                <Sidebar/> 
            </div>
              <div className=" bg-[#212121] flex-1 h-screen overflow-hidden relative text-gray-200">
                  <Header/>
                  {children}
              </div>
          </div> 
        </SessionProvider>     
      </body>
    </html>
  );
}
